import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { SELECTION } from '../scripts/generateFixture.js';
import { BOOKS, findBook } from '../src/books.js';

interface FixtureSelectionRow {
  readonly book: string;
  readonly chapters?: readonly number[];
  /** Single-verse selections as "chapter:verse" (P5.2/QR-3). */
  readonly verses?: readonly string[];
  readonly why: string;
}

interface FixtureVerse {
  readonly book_name: string;
  readonly book: number;
  readonly chapter: number;
  readonly verse: number;
  readonly text: string;
}

interface FixtureFile {
  readonly generatedFrom: {
    readonly translation: string;
    readonly sourceSha256: string;
    readonly note: string;
  };
  readonly selection: readonly FixtureSelectionRow[];
  readonly verses: readonly FixtureVerse[];
}

interface WebManifest {
  readonly id: string;
  readonly label: string;
  readonly sha256: string;
}

const FIXTURE_PATH = join(import.meta.dirname, '..', 'fixtures', 'web-subset.json');
const WEB_MANIFEST_PATH = join(import.meta.dirname, '..', 'manifests', 'web.json');
const EXPECTED_NOTE =
  'World English Bible (public domain). Subset generated by ' +
  'scripts/generateFixture.ts; see pipeline/manifests/web.json for rights.';

function readFixture(): FixtureFile {
  return JSON.parse(readFileSync(FIXTURE_PATH, 'utf8')) as FixtureFile;
}

function normalizeSelection(
  selection: readonly FixtureSelectionRow[],
): readonly { readonly book: string; readonly bookId: number; readonly chapters: readonly number[] }[] {
  const chaptersByBook = new Map<number, Set<number>>();
  for (const entry of selection) {
    const book = findBook(entry.book);
    if (!book) throw new Error(`Unknown selection book ${entry.book}`);
    const bucket = chaptersByBook.get(book.id) ?? new Set<number>();
    for (const chapter of entry.chapters ?? []) bucket.add(chapter);
    // A verse-level selection contributes its chapter to the chapter
    // universe; exactness of WHICH verses is asserted separately below.
    for (const locator of entry.verses ?? []) bucket.add(Number(locator.split(':')[0]));
    chaptersByBook.set(book.id, bucket);
  }

  return BOOKS
    .filter((book) => chaptersByBook.has(book.id))
    .map((book) => ({
      book: book.name,
      bookId: book.id,
      chapters: [...(chaptersByBook.get(book.id) ?? new Set<number>())].sort((left, right) => left - right),
    }));
}

function actualFixtureChapters(
  verses: readonly FixtureVerse[],
): readonly { readonly book: string; readonly bookId: number; readonly chapters: readonly number[] }[] {
  const chaptersByBook = new Map<number, Set<number>>();
  for (const verse of verses) {
    const bucket = chaptersByBook.get(verse.book) ?? new Set<number>();
    bucket.add(verse.chapter);
    chaptersByBook.set(verse.book, bucket);
  }

  return BOOKS
    .filter((book) => chaptersByBook.has(book.id))
    .map((book) => ({
      book: book.name,
      bookId: book.id,
      chapters: [...(chaptersByBook.get(book.id) ?? new Set<number>())].sort((left, right) => left - right),
    }));
}

describe('committed WEB fixture selection', () => {
  it('matches the generator selection and pinned source identity exactly', () => {
    const fixture = readFixture();
    const manifest = JSON.parse(readFileSync(WEB_MANIFEST_PATH, 'utf8')) as WebManifest;

    expect(manifest.id).toBe('web');
    expect(manifest.label).toBe('World English Bible');
    expect(fixture.generatedFrom).toEqual({
      translation: 'WEB',
      sourceSha256: manifest.sha256,
      note: EXPECTED_NOTE,
    });
    expect(fixture.selection).toEqual(SELECTION);
  });

  it('commits exactly 5,726 unique verses in canonical order for the selected chapter universe', () => {
    // 5,669 through P5.2; +58 at P5.6 PR 2 (Psalm 136's 26 + Genesis 11's 32,
    // the pericope-grouping fixture targets); -1 at the 2026-08-25 re-pin:
    // the fixture is now generated straight from the pinned VPL zip, whose
    // importer omits textless references, so the empty Luke 17:36 entry the
    // earlier USFM-extension path had carried is no longer emitted (the
    // WEB delta report proved every other verse byte-identical).
    const fixture = readFixture();
    const expectedSelection = normalizeSelection(SELECTION);
    const committedSelection = normalizeSelection(fixture.selection);
    const actualSelection = actualFixtureChapters(fixture.verses);

    expect(fixture.verses).toHaveLength(5726);
    expect(new Set(fixture.verses.map((verse) => `${verse.book}:${verse.chapter}:${verse.verse}`)).size).toBe(5726);
    expect(committedSelection).toEqual(expectedSelection);
    expect(actualSelection).toEqual(expectedSelection);

    // Verse-level selections must stay verse-level: a chapter reachable ONLY
    // through a verses: entry commits exactly the listed verses, never the
    // whole chapter (the P5.2 churn budget is per-verse, not per-chapter).
    const chapterSelected = new Map<number, Set<number>>();
    const verseSelected = new Map<number, Map<number, Set<number>>>();
    for (const entry of SELECTION) {
      const book = findBook(entry.book);
      if (!book) throw new Error(`Unknown selection book ${entry.book}`);
      const chapterBucket = chapterSelected.get(book.id) ?? new Set<number>();
      for (const chapter of entry.chapters ?? []) chapterBucket.add(chapter);
      chapterSelected.set(book.id, chapterBucket);
      for (const locator of entry.verses ?? []) {
        const [chapterText, verseText] = locator.split(':');
        const chapter = Number(chapterText);
        const perBook = verseSelected.get(book.id) ?? new Map<number, Set<number>>();
        const perChapter = perBook.get(chapter) ?? new Set<number>();
        perChapter.add(Number(verseText));
        perBook.set(chapter, perChapter);
        verseSelected.set(book.id, perBook);
      }
    }
    for (const [bookId, perBook] of verseSelected) {
      for (const [chapter, expectedVerses] of perBook) {
        if (chapterSelected.get(bookId)?.has(chapter)) continue;
        const committed = fixture.verses
          .filter((verse) => verse.book === bookId && verse.chapter === chapter)
          .map((verse) => verse.verse)
          .sort((left, right) => left - right);
        expect(committed).toEqual([...expectedVerses].sort((left, right) => left - right));
      }
    }

    for (const [index, verse] of fixture.verses.entries()) {
      expect(BOOKS[verse.book - 1]?.name).toBe(verse.book_name);
      if (index === 0) continue;
      const previous = fixture.verses[index - 1]!;
      const inCanonicalOrder =
        previous.book < verse.book ||
        (previous.book === verse.book && previous.chapter < verse.chapter) ||
        (previous.book === verse.book &&
          previous.chapter === verse.chapter &&
          previous.verse < verse.verse);
      expect(inCanonicalOrder).toBe(true);
    }
  });
});
