/**
 * Generates docs/ATTRIBUTIONS.md from the source manifests.
 *
 * Generated rather than written, for the same reason the manifests exist at
 * all: an acknowledgements page maintained by hand drifts from what the
 * artifact actually contains, and the moment it drifts it stops being an
 * attribution and becomes a claim. This one cannot disagree with the build,
 * because both read the same manifests.
 *
 * It also serves a legal purpose, not only a courteous one. OpenBible's data
 * is CC BY, which REQUIRES attribution in shipped output; this file is where
 * that requirement is discharged, and where the rights position of every
 * other source is stated in the open.
 *
 * Usage: npx tsx scripts/generateAttributions.ts
 */

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { EXPOSITION_SOURCES } from '../src/expositionSources.js';
import type { SourceManifest } from '../src/provenance/manifest.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, '..', 'docs', 'ATTRIBUTIONS.md');

const RIGHTS_LABEL: Readonly<Record<string, string>> = {
  public_domain: 'Public domain',
  cc_by: 'CC BY 4.0 — **attribution required**',
  cc_by_sa: 'CC BY-SA — attribution + share-alike',
  owned: 'Owned by Life Hope Church',
  editorial: 'Authored for this dataset',
  pd_text_claimed_transcription: 'Public-domain work, transcription carries a claim',
};

function main(): void {
  const manifests = readdirSync(join(ROOT, 'manifests'))
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map(
      (name) =>
        JSON.parse(readFileSync(join(ROOT, 'manifests', name), 'utf8')) as SourceManifest & {
          attributionNote?: string;
          provenanceNote?: string;
          retrievedAt?: string;
        },
    );

  const expositionIds = new Set(EXPOSITION_SOURCES.map((spec) => spec.id));
  const shipped = manifests.filter((manifest) => manifest.sha256);
  const declarative = manifests.filter((manifest) => !manifest.sha256);

  const section = (manifest: (typeof manifests)[number]): string =>
    [
      `### ${manifest.label}`,
      '',
      `- **Rights:** ${RIGHTS_LABEL[manifest.rightsClass] ?? manifest.rightsClass}`,
      manifest.sourceUrl ? `- **Source:** <${manifest.sourceUrl}>` : null,
      manifest.retrievedAt ? `- **Retrieved:** ${manifest.retrievedAt}` : null,
      manifest.sha256 ? `- **Checksum:** \`${manifest.sha256}\`` : null,
      '',
      manifest.licenseRecord,
      manifest.attributionNote ? `\n${manifest.attributionNote}` : '',
    ]
      .filter((line) => line !== null)
      .join('\n');

  const expositors = shipped.filter((manifest) => expositionIds.has(manifest.id));
  const others = shipped.filter((manifest) => !expositionIds.has(manifest.id));

  writeFileSync(
    OUT,
    `# Sources and acknowledgements

<!-- GENERATED by pipeline/scripts/generateAttributions.ts — do not hand-edit.
     Regenerate after changing any manifest. -->

This engine's understanding of Scripture is not its own. Every theme it
recognises and every term it treats as evidence comes from people who spent
their lives explaining the Bible, and from communities who catalogued it. This
page names them.

**What ships and what does not.** The commentaries and expositions below are
read only at BUILD time. Their prose never enters the published artifact and is
never read at query time. What ships is a distillate: a term, a score, a count,
and a pointer back to who attested it. That distinction is deliberate, and it
is why sources whose *transcriptions* carry restrictions can still inform the
statistics without their text being redistributed.

**Attribution is a requirement here, not a courtesy.** OpenBible.info's data is
CC BY 4.0, which requires attribution in shipped output. This file is where
that obligation is met.

---

## Expositors

The verse-level evidence layer. A term is admitted only when **two or more of
these authors, independently, used it about the same verse** — which is what
separates the passage's theology from any one writer's habits of speech.

**The bound on that independence, stated plainly:** every expositor below is an
18th- or 19th-century Protestant. Corroboration establishes independence of
*authorship* — Spurgeon cannot corroborate Spurgeon — but not independence of
*interpretive tradition*: authors who share a school of reading will agree for
reasons the corroboration rule cannot see. The evidence layer therefore
reflects consensus Protestant homiletics of that era, and the engine reports it
as such rather than as a neutral property of the text. The concept layer, where
provenance is per-anchor and editorial judgment is labeled as editorial, is
where any different or broader voice enters deliberately.

${expositors.map(section).join('\n\n')}

---

## Scripture text, topical data and cross-references

${others.map(section).join('\n\n')}

---

## Declared for lineage only

These are not imported. They are recorded so that sources deriving from them
can declare that lineage, which keeps the engine from counting the same
scholarship twice as independent evidence.

${declarative.map((manifest) => `- **${manifest.label}** — ${manifest.licenseRecord}`).join('\n')}

---

## What is deliberately absent

- **Modern sermon libraries.** Several offer their material free of charge —
  Life.Church Open among them — but free of charge is not the same as licensed
  for redistribution. Life.Church's terms grant use "for your internal use and
  not for resale" and forbid exercising the granted rights "toward commercial
  advantage", which does not permit a publicly distributed artifact. Recorded
  here so the question does not have to be re-asked.
- **Copyrighted translations.** NIV, ESV and similar cannot be included. This
  has a visible consequence: a verse remembered in NIV wording may not match
  the public-domain text the engine searches.
- **CCEL's own transcription files**, where an alternative source exists. Where
  one does not, see the rights note on the affected source above.
`,
    'utf8',
  );

  process.stdout.write(
    `Wrote ${OUT}\n  ${expositors.length} expositors, ${others.length} data sources, ` +
      `${declarative.length} lineage-only\n`,
  );
}

main();
