/**
 * Derives the KJV versification table from eBible's KJV export.
 *
 * Why derived rather than hand-entered: the table is 1,189 numbers, and a
 * single wrong one silently shifts every SWORD commentary entry after it by a
 * verse. Typing it out is exactly the kind of task that produces a defect
 * nobody can see. Deriving it from a checksummed published text means the
 * table is reproducible and its errors would have to be the publisher's.
 *
 * The output is committed, because the KJV's versification is fixed — this is
 * not a build-time input that changes, it is a constant we are recording the
 * provenance of.
 *
 * Usage: npx tsx scripts/generateKjvVersification.ts
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { BOOKS } from '../src/books.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'src', 'versification', 'kjv.ts');

/** eBible's legacy three-letter codes, restricted to the 66-book canon. */
const CODES: Readonly<Record<string, number>> = {
  GEN: 1, EXO: 2, LEV: 3, NUM: 4, DEU: 5, JOS: 6, JDG: 7, RUT: 8,
  '1SA': 9, '2SA': 10, '1KI': 11, '2KI': 12, '1CH': 13, '2CH': 14,
  EZR: 15, NEH: 16, EST: 17, JOB: 18, PSA: 19, PRO: 20, ECC: 21, SOL: 22,
  ISA: 23, JER: 24, LAM: 25, EZE: 26, DAN: 27, HOS: 28, JOE: 29, AMO: 30,
  OBA: 31, JON: 32, MIC: 33, NAH: 34, HAB: 35, ZEP: 36, HAG: 37, ZEC: 38,
  MAL: 39, MAT: 40, MAR: 41, LUK: 42, JOH: 43, ACT: 44, ROM: 45,
  '1CO': 46, '2CO': 47, GAL: 48, EPH: 49, PHI: 50, COL: 51, '1TH': 52,
  '2TH': 53, '1TI': 54, '2TI': 55, TIT: 56, PHM: 57, HEB: 58, JAM: 59,
  '1PE': 60, '2PE': 61, '1JO': 62, '2JO': 63, '3JO': 64, JUD: 65, REV: 66,
};

function main(): void {
  const path = process.argv[2] ?? join(ROOT, 'sources', 'kjv', 'eng-kjv_vpl.txt');
  const raw = readFileSync(path);
  const sha256 = createHash('sha256').update(raw).digest('hex');

  const highest = new Map<string, number>();
  for (const line of raw.toString('utf8').split(/\r?\n/)) {
    const match = /^([1-3]?[A-Z]{2,3}) (\d+):(\d+)/.exec(line);
    if (!match) continue;
    const bookId = CODES[match[1] as string];
    if (!bookId) continue; // Apocrypha: present in this export, outside our canon.
    const key = `${bookId}:${match[2]}`;
    highest.set(key, Math.max(highest.get(key) ?? 0, Number(match[3])));
  }

  const table: number[][] = [];
  for (const book of BOOKS) {
    const chapters: number[] = [];
    for (let chapter = 1; chapter <= book.chapterCount; chapter += 1) {
      const count = highest.get(`${book.id}:${chapter}`);
      if (count === undefined) {
        throw new Error(`generateKjvVersification: no verses for ${book.name} ${chapter}`);
      }
      chapters.push(count);
    }
    table.push(chapters);
  }

  const verses = table.flat().reduce((sum, n) => sum + n, 0);
  const chapters = table.flat().length;
  // Canonical KJV totals. If the source ever disagrees, the source is wrong
  // or is not the KJV, and either way this must not silently produce a table.
  if (verses !== 31102 || chapters !== 1189 || table.length !== 66) {
    throw new Error(
      `generateKjvVersification: expected 66 books / 1189 chapters / 31102 verses, ` +
        `derived ${table.length} / ${chapters} / ${verses}`,
    );
  }

  const body = table
    .map((chapters_, index) => {
      const book = BOOKS[index]!;
      return `  /* ${String(book.id).padStart(2)} ${book.name} */ [${chapters_.join(', ')}],`;
    })
    .join('\n');

  writeFileSync(
    OUT,
    `/**
 * KJV versification: verses per chapter, indexed by book id - 1.
 *
 * GENERATED by scripts/generateKjvVersification.ts — do not hand-edit.
 * Derived from eBible.org's KJV verse-per-line export,
 * sha256 ${sha256}.
 *
 * This exists because SWORD commentary modules index their entries against
 * KJV versification. Entry n maps to a verse only if this table is exact: one
 * wrong number shifts every subsequent comment by a verse, silently, with the
 * commentary still looking plausible against the wrong text.
 *
 * Totals are asserted at module load (66 books, 1189 chapters, 31102 verses),
 * so a corrupted edit fails immediately rather than at the point of use.
 */

export const KJV_VERSES_PER_CHAPTER: readonly (readonly number[])[] = [
${body}
];

const bookCount = KJV_VERSES_PER_CHAPTER.length;
const chapterCount = KJV_VERSES_PER_CHAPTER.reduce((sum, book) => sum + book.length, 0);
const verseCount = KJV_VERSES_PER_CHAPTER.reduce(
  (sum, book) => sum + book.reduce((inner, verses) => inner + verses, 0),
  0,
);
if (bookCount !== 66 || chapterCount !== 1189 || verseCount !== 31102) {
  throw new Error(
    \`kjv versification table is corrupt: \${bookCount} books, \${chapterCount} chapters, \` +
      \`\${verseCount} verses (expected 66 / 1189 / 31102)\`,
  );
}

/** Verses in a chapter, or undefined if the reference is outside the canon. */
export function kjvVerseCount(bookId: number, chapter: number): number | undefined {
  return KJV_VERSES_PER_CHAPTER[bookId - 1]?.[chapter - 1];
}
`,
    'utf8',
  );

  process.stdout.write(
    `Wrote ${OUT}\n  ${table.length} books, ${chapters} chapters, ${verses} verses\n` +
      `  source sha256 ${sha256}\n`,
  );
}

main();
