/**
 * Distills STEPBible's TVTMS versification catalogue into a committed module.
 *
 * TVTMS ("Translators Versification Traditions with Methodology for
 * Standardisation", CC BY 4.0 — credit "STEP Bible", www.STEPBible.org) is a
 * 5.8 MB catalogue covering Hebrew, Greek, Latin and other traditions. The
 * versification guard needs only the English-relevant loci, and only their
 * five structural columns — so this script parses the sha-verified download
 * once and commits the distillate, for the same reasons the KJV table is
 * committed: `npm run verify` stays hermetic (no gitignored source needed),
 * and the exact bytes the guard reasons over are reviewable in the diff.
 *
 * Committing the distillate is also how the license's soft ask is honored:
 * CC BY asks that changes be "recorded and made available", and both this
 * script and its diffable output live in the repository.
 *
 * The script verifies the download against the stepbible-tvtms manifest pin
 * BEFORE parsing — a distillate regenerated from unverified bytes would carry
 * the manifest's provenance while describing something else.
 *
 * Usage: npx tsx scripts/generateTvtmsDistillate.ts [path-to-tvtms.txt]
 */

import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { SourceManifest } from '../src/provenance/manifest.js';
import { parseTvtmsExpanded } from '../src/versificationGuard.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const OUT = join(ROOT, 'src', 'versification', 'tvtms.ts');

function main(): void {
  const manifest = JSON.parse(
    readFileSync(join(ROOT, 'manifests', 'stepbible-tvtms.json'), 'utf8'),
  ) as SourceManifest;

  const path = process.argv[2] ?? join(ROOT, 'sources', 'stepbible-tvtms.txt');
  const raw = readFileSync(path);
  const sha256 = createHash('sha256').update(raw).digest('hex');
  if (sha256 !== manifest.sha256) {
    throw new Error(
      `generateTvtmsDistillate: ${path} has sha256 ${sha256}, but the ` +
        `stepbible-tvtms manifest pins ${manifest.sha256} — refusing to distill `
        + 'unverified bytes',
    );
  }

  const loci = parseTvtmsExpanded(raw.toString('utf8'));
  const rowCount = loci.reduce((sum, locus) => sum + locus.rows.length, 0);

  const lines: string[] = [
    '/**',
    ' * TVTMS English-relevant versification loci.',
    ' *',
    ' * GENERATED by scripts/generateTvtmsDistillate.ts — do not hand-edit.',
    " * Distilled from STEPBible's TVTMS catalogue (CC BY 4.0 — credit",
    ' * "STEP Bible", www.STEPBible.org),',
    ` * sha256 ${manifest.sha256}.`,
    ' *',
    ' * Only the five structural columns survive the distillation (SourceType,',
    ' * SourceRef, StandardRef, Action, Tests) and only for loci with at least',
    ' * one English-tradition row — every prose/note column is dropped at parse',
    ' * time, and nothing here ships in the artifact (the guard is build-time',
    ' * only; see versificationGuard.ts).',
    ' *',
    ' * Totals are asserted at module load, so a corrupted edit fails',
    ' * immediately rather than by silently weakening the guard.',
    ' */',
    '',
    "import type { TvtmsLocus } from '../versificationGuard.js';",
    '',
    'export const TVTMS_ENGLISH_LOCI: readonly TvtmsLocus[] = [',
  ];
  for (const locus of loci) {
    lines.push(`  { id: ${JSON.stringify(locus.id)}, rows: [`);
    for (const row of locus.rows) {
      lines.push(
        `    { sourceType: ${JSON.stringify(row.sourceType)}, ` +
          `sourceRef: ${JSON.stringify(row.sourceRef)}, ` +
          `standardRef: ${JSON.stringify(row.standardRef)}, ` +
          `action: ${JSON.stringify(row.action)}, ` +
          `tests: ${JSON.stringify(row.tests)} },`,
      );
    }
    lines.push('  ] },');
  }
  lines.push('];');
  lines.push('');
  lines.push(`const EXPECTED_LOCI = ${loci.length};`);
  lines.push(`const EXPECTED_ROWS = ${rowCount};`);
  lines.push('const actualRows = TVTMS_ENGLISH_LOCI.reduce((sum, locus) => sum + locus.rows.length, 0);');
  lines.push('if (TVTMS_ENGLISH_LOCI.length !== EXPECTED_LOCI || actualRows !== EXPECTED_ROWS) {');
  lines.push('  throw new Error(');
  lines.push('    `tvtms distillate corrupted: ${TVTMS_ENGLISH_LOCI.length} loci / ${actualRows} rows, ` +');
  lines.push('      `expected ${EXPECTED_LOCI} / ${EXPECTED_ROWS} — regenerate with scripts/generateTvtmsDistillate.ts`,');
  lines.push('  );');
  lines.push('}');
  lines.push('');

  writeFileSync(OUT, lines.join('\n'));
  process.stdout.write(
    `wrote ${OUT}: ${loci.length} English-relevant loci, ${rowCount} structural rows, ` +
      `from verified sha256 ${sha256.slice(0, 12)}…\n`,
  );
}

main();
